language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - ng build --prod --base-href "https://theargex.github.io/stargit2.0/"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
