name: Semantic Release

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    
    steps:
    - uses: brpaz/action-semantic-release@v1
    - with:
        dry_run: "false"
        install_plugins: "release-notes-generator semantic-release-gcr"
        branch: master
